/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mbrained;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author siddh
 */
public class Customer extends javax.swing.JFrame {

    dbconnect db;
    ArrayList<String[]> cartArr;
    String[][] bill;
    String cname;
    /**
     * Creates new form Customer
     */
    
    
    public Customer(String cname) {
         this();
        this.cname=cname;
    }

    private Customer() {
        initComponents();
        warn.setVisible(false);
       veg.setVisible(false);
       nonveg.setVisible(false);
       }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
     public String[][] combArray2()
    {


        String[][] ret = null;
        
        //String[] temp = new String[4];
        
        try {
            
            db.connect();
            //System.out.println("No issue here");
            ResultSet rs=db.fetch("Select price from menu where name='"+type.getSelectedItem()+"'");
            
            rs.next();
            int avail=100000;
            int p=rs.getInt(1);
            
            int qty = (Integer)Spin.getValue();
                    
            if(qty<=avail)
            {
                    warn.setVisible(false);
                 // System.out.println("####################");
                    cartArr.add(new String[] {(String)type.getSelectedItem(),qty+"",p+" ",(qty*p)+" "});
            }
            else
            {
            warn.setVisible(true);
            }
           
        } catch (ClassNotFoundException ex) {
          //  Logger.getLogger(updateStock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            //Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ret= new String[cartArr.size()][4];
        
        for(int i=0;i<cartArr.size();i++)
        {
        ret[i]=cartArr.get(i);
        System.out.println("");
        }
           bill=ret;
            return ret;
    }

    
     private String[] combArray()
    {
        String[] ret;
        
        ArrayList<String> arr= new ArrayList<>();
        
        try {
            
            db.connect();
            //System.out.println("No issue here");
            ResultSet rs=db.fetch("Select name from menu");
            
            try {
                while(rs.next())
                {
                    arr.add(rs.getString(1));
                }
            } catch (SQLException ex) {
               // Logger.getLogger(updateStock.class.getName()).log(Level.SEVERE, null, ex);
            }
            
           
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(updateStock.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ret=new String[arr.size()];
       // System.out.println("jdfhd");
           int i=0;
           while(i!=arr.size())
           {
               ret[i]= arr.get(i);
               i++;
           }
           
         //  System.out.println(ret);
           
            return ret;
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        db= new dbconnect();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        type = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        warn = new javax.swing.JLabel();
        Spin = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,100000,1));
        update = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cart = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        veg = new javax.swing.JLabel();
        nonveg = new javax.swing.JLabel();

        cartArr= new ArrayList<String[]>();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeItemStateChanged(evt);
            }
        });
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Quantity");

        warn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        warn.setForeground(new java.awt.Color(255, 0, 51));
        warn.setText("Requested Quantity not available");

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("Order Now");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        update1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update1.setText("Add to Cart");
        update1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });

          type.setModel(new javax.swing.DefaultComboBoxModel<>(this.combArray()));
      
        // cart.setModel(new javax.swing.table.DefaultTableModel(
        //     new Object [][] {
        //         {null, null, null, null},
        //         {null, null, null, null},
        //         {null, null, null, null},
        //         {null, null, null, null}
        //     },
        //     new String [] {
        //         "Title 1", "Title 2", "Title 3", "Title 4"
        //     }
        // ));
        jScrollPane1.setViewportView(cart);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Item Name");

        veg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mbrained/veg.png"))); // NOI18N

        nonveg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mbrained/non veg.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(update1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nonveg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(Spin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(warn, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(warn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nonveg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       
        if(bill!=null)
        { 
         (new CBill(this.bill,this.cname)).setVisible(true);
         this.setVisible(false);
        }
           
    }//GEN-LAST:event_updateActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) 
    {

//GEN-FIRST:event_update1ActionPerformed
            cart.setModel(new javax.swing.table.DefaultTableModel(
            this.combArray2(),
            new String [] {
                "Name","Price","Quantity","Total"
            }
        ));
            repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_update1ActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeItemStateChanged
        try {
            // TODO add your handling code here:
            
            db.connect();
            
            ResultSet rs= db.fetch("Select Category from menu where name='"+type.getSelectedItem()+"'");
            
            rs.next();
            if(rs.getString(1).equals("NON-VEGETARIAN"))
            {
                nonveg.setVisible(true);
                veg.setVisible(false);
            }
            else
            {
                veg.setVisible(true);
                nonveg.setVisible(false);
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_typeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spin;
    private javax.swing.JTable cart;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nonveg;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton update;
    private javax.swing.JButton update1;
    private javax.swing.JLabel veg;
    private javax.swing.JLabel warn;
    // End of variables declaration//GEN-END:variables
}
